apiVersion: ziggiz.io/v1alpha1
kind: BucketClaim
metadata:
  name: matdavey-golden-bucket-award
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: default
spec:
  resourceRef:
    name: matdavey-golden-bucket-award
  parameters:
    region: us-east-1
