apiVersion: v1
kind: Secret
metadata:
  name: localstack-aws-secret
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook-delete-policy: HookFailed
type: Opaque
data:
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gdGVzdAphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSB0ZXN0Cg==
---
apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-aws-secret
      key: creds
  endpoint:
    hostnameImmutable: true
    url:
      type: Static
      static: http://192.168.215.2:4566
