apiVersion: ziggiz.io/v1alpha1
kind: BucketWithQueueClaim
metadata:
  name: matdavey-bucket-with-queue
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  parameters:
    region: us-east-1
    # Override the default events list if needed, e.g:
    # events:
    #   - "s3:ObjectCreated:*"
    #   - "s3:ObjectRemoved:*"
